#!/usr/bin/env python3
"""Build a Klunk syllabus model from a NESA Stage 6 syllabus .docx.

Klunk ships no syllabus models. A syllabus document is copyright, and the NESA
Stage 6 (2013) notice permits a NSW teacher to copy reasonable portions for
bona fide study while forbidding reproduction of a major extract, modification,
and commercial use. A complete content inventory republished on the public web
is none of those things, so the model is generated by each teacher from their
own copy, into their own folder.

That constraint produced a better tool than bundling would have. Every NESA
Stage 6 syllabus from the 2013 era uses the same three-column content table:

    | Outcomes | Students learn about: | Students learn to: |

so this reads Design and Technology, Industrial Technology, Food Technology,
Textiles and Design and Agriculture without changes. The outcome cell is blank
on continuation rows, meaning the outcome above still applies, and each
"learn about" cell is a topic heading followed by its content points.

Stdlib only, so it runs on any Python 3.11+ with no network access. That matters
on a locked-down school machine.

Usage:
    python3 nesa_stage6_syllabus.py <syllabus.docx> --id nsw-hsc-design-technology
    python3 nesa_stage6_syllabus.py <syllabus.docx> --id ... --out syllabus/dt.json
    python3 nesa_stage6_syllabus.py <syllabus.docx> --id ... --source-url https://...
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
import zipfile
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Iterator

FORMAT_VERSION = "1"
DOC_TYPE = "klunk_syllabus"

# Field instructions and deleted runs carry text that is never visible in Word.
# Table-of-contents entries are where a naive extractor picks them up and emits
# a line of raw markup.
DROP_RE = re.compile(r"<w:instrText.*?</w:instrText>|<w:delText.*?</w:delText>", re.S)
TAG_RE = re.compile(r"<[^>]+>")

# A paragraph's visible text, in document order: the runs themselves, and the
# two things between runs that are a space on the page.
#
# Replacing those two in the XML before reading the runs looked like it worked
# and did nothing at all, because only <w:t> contents are collected: the space
# landed between elements and was thrown away with the rest of the markup. So
# "Design inspiration<tab>including:" arrived as "Design inspirationincluding:",
# and the syllabus is full of them.
#
# `<w:tab/>` only, never `<w:tab w:val="left" w:pos="999"/>`: the second is a
# tab stop in the paragraph's properties, not a tab in its text.
TEXT_RE = re.compile(r"<w:t(?: [^>]*)?>(.*?)</w:t>|<w:tab/>|<w:br(?: [^>]*)?/>", re.S)
PARA_RE = re.compile(r"<w:p(?: [^>]*)?>.*?</w:p>|<w:p(?: [^>]*)?/>", re.S)
ROW_RE = re.compile(r"<w:tr(?: [^>]*)?>.*?</w:tr>", re.S)
CELL_RE = re.compile(r"<w:tc(?: [^>]*)?>.*?</w:tc>", re.S)
TABLE_RE = re.compile(r"<w:tbl(?: [^>]*)?>.*?</w:tbl>", re.S)

# "P1.1examines design theory and practice" - the code and its text sit in
# separate runs of one paragraph, so they arrive concatenated.
OUTCOME_RE = re.compile(r"^([A-Z]{1,2}\d+\.\d+)\s*(.*)$", re.S)

# Which course a content table belongs to is stated in the heading above it.
# Not anchored to the start: Word concatenates the section number onto the
# heading text, so the paragraph reads "8Content: ... Preliminary Course".
# Table-of-contents entries match this too, but they all appear before the
# tables and each heading overwrites the last, so the nearest one still wins.
COURSE_HEADING_RE = re.compile(r"Content:.*?\b(Preliminary|HSC)\b", re.I)

# Industrial Technology never writes "Content: ... HSC". It splits the course
# into focus areas and marks each one "Focus Area: Automotive Technologies
# (Preliminary)" or "... (HSC)". Without this, every focus area inherits the
# last Content: heading and the whole Preliminary half is filed under HSC.
COURSE_MARKER_RE = re.compile(r"\((Preliminary|HSC)\)", re.I)

# The group a topic sits in, taken only from a heading that says it is one.
#
# This used to accept any short paragraph that did not end in a full stop, on the
# theory that a heading looks different from prose. It does not look different
# enough. Design and Technology filed all forty of its topics under
# "7.2Key Competencies", a numbered section heading from the document furniture,
# and Textiles picked up a stray line listing footwear trades for three of its
# topics. Both syllabuses label their real groups, so the label is the signal:
# Textiles writes "Area of Study: Design", Industrial Technology writes
# "Focus Area: Automotive Technologies (Preliminary)".
#
# Design and Technology has neither, and should not: it is one content table per
# course, so there is nothing for a group to divide. No label means no group.
FOCUS_AREA_RE = re.compile(
    r"^\s*(?:\d+(?:\.\d+)*\s*)?(?:area\s+of\s+study|focus\s+area)\s*[:–—-]\s*(.+)$",
    re.I,
)

# "Focus Area: Automotive Technologies (Preliminary)" names the course too, and
# that belongs to the course, not to the name of the area.
COURSE_SUFFIX_RE = re.compile(r"\s*\((?:Preliminary|HSC)\)\s*$", re.I)

# A topic heading often ends by announcing its own list.
TRAILING_NOISE_RE = re.compile(r"[,;]?\s*includ(?:ing|es)\s*[:;.]?\s*$", re.I)

# A row whose "Students learn about" cell opens with a list marker is not a new
# topic. It is the tail of the one above, which ran past the bottom of a page:
# Word starts a fresh table row after the break, and the list carries on from
# where it stopped. Textiles HSC does this once, at "iv)", and the row was read
# as a topic named after a content point with the five points that followed it
# hanging underneath.
#
# The same shape as the "Question N (continued)" blocks in the past papers, and
# the same rule: merge into the parent rather than register a new one.
#
# Only a marker in brackets, which is what NESA prints. A full stop after the
# numeral would also match "i.e." at the start of a heading.
CONTINUATION_RE = re.compile(r"^\s*(?:[ivxlcdm]+|[a-z]|\d+)\)")

CONTENT_HEADERS = ("outcomes", "students learn about", "students learn to")


@dataclass(frozen=True, slots=True)
class Point:
    """One content point beneath a topic."""

    id: str
    text: str


@dataclass(slots=True)
class Topic:
    """A topic heading, its content points, and the outcomes it serves."""

    id: str
    name: str
    text: str
    group: str = ""
    outcomes: list[str] = field(default_factory=list)
    points: list[Point] = field(default_factory=list)
    skills: list[str] = field(default_factory=list)


@dataclass(slots=True)
class Course:
    """A course within the syllabus, e.g. Preliminary or HSC."""

    id: str
    name: str
    outcomes: dict[str, str] = field(default_factory=dict)
    topics: list[Topic] = field(default_factory=list)


def para_text(xml: str) -> str:
    """Return the visible text of one paragraph.

    Args:
        xml: The raw ``<w:p>`` element.

    Returns:
        Runs joined, tabs and breaks flattened to spaces, entities decoded.
    """
    xml = DROP_RE.sub("", xml)
    parts = [
        " " if m.group(1) is None else TAG_RE.sub("", m.group(1))
        for m in TEXT_RE.finditer(xml)
    ]
    text = html.unescape("".join(parts))
    # A tab beside a typed space is one gap on the page, not two. Only runs of
    # ordinary spaces: a non-breaking space is published punctuation and stays
    # exactly where NESA put it.
    return re.sub(r"[ \t]{2,}", " ", text).strip()


def cell_lines(xml: str) -> list[str]:
    """Return one entry per non-empty paragraph in a table cell.

    Paragraph boundaries are the content structure. The first paragraph of a
    "Students learn about" cell is the topic heading and the rest are its
    content points, so joining them into one string discards the only signal
    that says which is which.

    Args:
        xml: The raw ``<w:tc>`` element.

    Returns:
        The cell's paragraphs, blanks removed.
    """
    return [t for t in (para_text(p) for p in PARA_RE.findall(xml)) if t]


def iter_blocks(xml: str) -> Iterator[tuple[str, object]]:
    """Yield ``("para", text)`` and ``("table", rows)`` in document order.

    Args:
        xml: The document body XML.

    Yields:
        Paragraphs outside tables, and tables as lists of rows of cells.
    """
    spans: list[tuple[int, int, str, str]] = [
        (m.start(), m.end(), "table", m.group(0)) for m in TABLE_RE.finditer(xml)
    ]
    covered = [(s, e) for s, e, _, _ in spans]

    for m in PARA_RE.finditer(xml):
        if not any(s <= m.start() < e for s, e in covered):
            spans.append((m.start(), m.end(), "para", m.group(0)))

    for _, _, kind, raw in sorted(spans, key=lambda s: s[0]):
        if kind == "para":
            if text := para_text(raw):
                yield "para", text
        else:
            rows = [
                cells
                for r in ROW_RE.findall(raw)
                if any(cells := [cell_lines(c) for c in CELL_RE.findall(r)])
            ]
            if rows:
                yield "table", rows


def table_layout(rows: list[list[list[str]]]) -> str | None:
    """Identify which content-table layout a table uses, if any.

    NESA Stage 6 (2013) syllabuses use two layouts, and a generator that assumes
    either one silently handles half the faculty:

    ``wide``
        One table per course, three columns, ``Outcomes | Students learn about |
        Students learn to``. The outcome cell is blank on continuation rows.
        Design and Technology.

    ``narrow``
        Many small tables, two columns, ``Students learn about | Students learn
        to``, no outcome column at all. Each row is one topic, and the outcomes
        appear as ordinary paragraphs above the table. Industrial Technology,
        Textiles and Design, Food Technology.

    Args:
        rows: The table, header row first.

    Returns:
        ``"wide"``, ``"narrow"``, or None if this is not a content table.
    """
    if not rows:
        return None
    header = [" ".join(c).strip().lower().rstrip(":") for c in rows[0]]

    if len(header) >= 3 and all(
        h.startswith(want) for h, want in zip(header, CONTENT_HEADERS)
    ):
        return "wide"

    if len(header) >= 2 and all(
        h.startswith(want) for h, want in zip(header, CONTENT_HEADERS[1:])
    ):
        return "narrow"

    return None


def course_of(codes: list[str], hint: str | None) -> tuple[str, str]:
    """Decide which course a block of content belongs to.

    In the narrow layout nothing names the course, but the outcome codes do:
    NESA prefixes Preliminary outcomes with P and HSC outcomes with H. Falling
    back to the nearest "Content: ... Preliminary/HSC" heading covers the wide
    layout and anything that breaks the convention.

    Args:
        codes: Outcome codes in scope, e.g. ``["P1.1", "P4.2"]``.
        hint: The most recent course heading, if one was seen.

    Returns:
        A ``(slug, display name)`` pair.
    """
    letters = {c[0].upper() for c in codes if c}
    if letters == {"P"}:
        return "pre", "Preliminary course"
    if letters == {"H"}:
        return "hsc", "HSC course"
    if hint:
        low = hint.lower()
        if low.startswith("prelim"):
            return "pre", "Preliminary course"
        if low.startswith("hsc"):
            return "hsc", "HSC course"
    return "course", "Course"


def tidy_name(heading: str) -> str:
    """Strip a heading's trailing "including:" so it reads as a label.

    The verbatim heading is kept separately, because this is an edit and the
    original still has to be checkable against the syllabus.

    Args:
        heading: The heading exactly as published.

    Returns:
        The heading without its trailing list announcement or punctuation, and
        with its whitespace flattened.
    """
    name = TRAILING_NOISE_RE.sub("", heading).strip().rstrip(":;.,").strip()
    # The .docx is full of non-breaking spaces. They are invisible on screen, so
    # a name carrying one looks identical to a name without and does not match
    # it. `text` keeps the heading exactly as published; this is the label.
    return " ".join(name.split())


def focus_area_name(captured: str) -> str:
    """Tidy the name captured from a focus-area heading.

    The label itself ("Area of Study:") is dropped by the pattern, since it names
    the kind of thing rather than this one. What is left can still carry the
    course in brackets and the non-breaking spaces the .docx is full of, which
    are invisible on screen and make two spellings of the same area look like
    two areas.

    Args:
        captured: The text following the focus-area label.

    Returns:
        The name of the area, whitespace flattened and course marker removed.
    """
    name = COURSE_SUFFIX_RE.sub("", captured)
    return " ".join(name.split()).strip().rstrip(":;.,").strip()


def add_topic(
    course: Course,
    about: list[str],
    skills: list[str],
    outcomes: list[str],
    group: str = "",
) -> None:
    """Append one topic to a course.

    The first paragraph of a "Students learn about" cell is the topic heading
    and the rest are its content points. Both layouts agree on that, which is
    why they can share this.

    Args:
        course: Course to extend. Topic numbering continues from its length, so
            a course spread over many tables still numbers straight through.
        about: The "Students learn about" cell, one entry per paragraph.
        skills: The "Students learn to" cell.
        outcomes: Outcome codes in scope for this topic.
        group: The section or focus area the topic sits under. Industrial
            Technology repeats topic names across eight focus areas, so without
            this a teacher browsing 146 flat topics cannot tell Automotive from
            Electronics.
    """
    if not about:
        return

    heading, *points = about

    # A continuation of the topic above, not a topic. Everything in the cell is
    # content, the heading line included, and the "learn to" cell belongs to the
    # same topic as well. Nothing to continue means the document opened with one,
    # which no NESA syllabus does; taking it as a topic is then the only reading
    # left and loses nothing.
    if course.topics and CONTINUATION_RE.match(heading):
        parent = course.topics[-1]
        start = len(parent.points)
        parent.points.extend(
            Point(id=f"{parent.id}.{start + i:02d}", text=p)
            for i, p in enumerate(about, 1)
        )
        parent.skills.extend(skills)
        return

    topic = Topic(
        id=f"{course.id.upper()}-{len(course.topics) + 1:02d}",
        name=tidy_name(heading),
        text=heading,
        group=group,
        outcomes=list(outcomes),
        skills=list(skills),
    )
    topic.points = [
        Point(id=f"{topic.id}.{i:02d}", text=p) for i, p in enumerate(points, 1)
    ]
    course.topics.append(topic)


def add_wide_table(course: Course, rows: list[list[list[str]]], group: str = "") -> None:
    """Add a three-column table, where each row may carry its own outcome.

    Args:
        course: Course to extend.
        rows: The table, header row included.
    """
    current: list[str] = []

    for row in rows[1:]:
        if len(row) < 3:
            continue

        if cell := " ".join(row[0]).strip():
            if m := OUTCOME_RE.match(cell):
                code, text = m.group(1), m.group(2).strip()
                course.outcomes.setdefault(code, text)
                current = [code]

        add_topic(course, row[1], row[2], current, group)


def add_narrow_table(
    course: Course,
    rows: list[list[list[str]]],
    outcomes: list[str],
    group: str = "",
) -> None:
    """Add a two-column table, where every row is a topic.

    Args:
        course: Course to extend.
        rows: The table, header row included.
        outcomes: Outcome codes gathered from the paragraphs above the table,
            which apply to every topic in it.
    """
    for row in rows[1:]:
        if len(row) < 2:
            continue
        add_topic(course, row[0], row[1], outcomes, group)


def parse(path: Path) -> list[Course]:
    """Read the syllabus and return its courses in document order.

    Args:
        path: The .docx file.

    Returns:
        One course per content table found.

    Raises:
        ValueError: If no content table is present, which means the document is
            not a 2013-era NESA Stage 6 syllabus.
    """
    with zipfile.ZipFile(path) as z:
        xml = z.read("word/document.xml").decode("utf8")

    courses: dict[str, Course] = {}
    hint: str | None = None
    # Outcomes stated as plain paragraphs since the last content table. In the
    # narrow layout this is the only place they appear.
    pending: dict[str, str] = {}

    group = ""

    for kind, value in iter_blocks(xml):
        if kind == "para":
            assert isinstance(value, str)
            if m := COURSE_HEADING_RE.search(value):
                hint = m.group(1)
            elif m := OUTCOME_RE.match(value):
                pending.setdefault(m.group(1), m.group(2).strip())
            else:
                # A focus-area marker names the course as well as the group, and
                # is the only course signal Industrial Technology gives.
                if m := COURSE_MARKER_RE.search(value):
                    hint = m.group(1)
                if m := FOCUS_AREA_RE.match(value):
                    group = focus_area_name(m.group(1))
            continue

        assert isinstance(value, list)
        layout = table_layout(value)
        if layout is None:
            continue

        codes = list(pending)
        slug, display = course_of(codes, hint)
        course = courses.setdefault(slug, Course(id=slug, name=display))

        if layout == "wide":
            add_wide_table(course, value, group)
        else:
            for code, text in pending.items():
                course.outcomes.setdefault(code, text)
            add_narrow_table(course, value, codes, group)

        pending = {}

    if not courses:
        raise ValueError(
            "no 'Students learn about / Students learn to' table found; "
            "this does not look like a NESA Stage 6 (2013) syllabus"
        )

    # Preliminary before HSC, then anything unrecognised, so output order is
    # stable regardless of how the document happened to be laid out.
    order = {"pre": 0, "hsc": 1}
    return [c for _, c in sorted(courses.items(), key=lambda kv: order.get(kv[0], 9))]


def to_model(courses: list[Course], args: argparse.Namespace) -> dict[str, object]:
    """Assemble the JSON model.

    Args:
        courses: Parsed courses.
        args: Parsed command line, supplying identity and provenance.

    Returns:
        A dict matching schemas/syllabus.schema.json.
    """
    source: dict[str, object] = {
        "title": args.source_title or Path(args.docx).name,
        "retrieved": args.retrieved or date.today().isoformat(),
        "licence": args.licence,
        # Never assume otherwise. A syllabus is copyright unless its publisher
        # has clearly said it may be republished, and Klunk reads this flag
        # before it will bundle anything.
        "redistributable": False,
    }
    if args.source_url:
        source["url"] = args.source_url

    return {
        "formatVersion": FORMAT_VERSION,
        "type": DOC_TYPE,
        "id": args.id,
        "name": args.name,
        "framework": args.framework,
        "authority": args.authority,
        "syllabusVersion": args.syllabus_version,
        "source": source,
        "courses": [
            {
                "id": c.id,
                "name": c.name,
                "outcomes": [
                    {"code": code, "text": text} for code, text in c.outcomes.items()
                ],
                "topics": [
                    {
                        "id": t.id,
                        "name": t.name,
                        "text": t.text,
                        **({"group": t.group} if t.group else {}),
                        "outcomes": t.outcomes,
                        "points": [{"id": p.id, "text": p.text} for p in t.points],
                        "skills": t.skills,
                    }
                    for t in c.topics
                ],
            }
            for c in courses
        ],
    }


def main(argv: list[str] | None = None) -> int:
    """Entry point.

    Args:
        argv: Argument list, defaulting to ``sys.argv[1:]``.

    Returns:
        0 on success, 2 on a usage or parsing failure.
    """
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("docx", type=Path, help="the syllabus .docx")
    ap.add_argument("--id", required=True, help="slug, e.g. nsw-hsc-design-technology")
    ap.add_argument("--name", default="", help="course name; defaults from --id")
    ap.add_argument("--framework", default="NESA")
    ap.add_argument("--authority", default="NSW Education Standards Authority")
    ap.add_argument("--syllabus-version", default="Stage 6 (2013)")
    ap.add_argument("--source-title", default="")
    ap.add_argument("--source-url", default="")
    ap.add_argument("--retrieved", default="", help="ISO date; defaults to today")
    ap.add_argument(
        "--licence",
        default="NSW Education Standards Authority, Crown copyright. Not redistributable.",
    )
    ap.add_argument("--out", type=Path, help="output file; defaults to stdout")
    args = ap.parse_args(argv)

    if not args.docx.is_file():
        print(f"no such file: {args.docx}", file=sys.stderr)
        return 2

    if not args.name:
        args.name = args.id.replace("-", " ").title()

    try:
        courses = parse(args.docx)
    except (ValueError, KeyError, zipfile.BadZipFile) as exc:
        # A wrong or corrupt file is the expected failure here, and the useful
        # recovery is a plain message rather than a traceback.
        print(f"could not read {args.docx}: {exc}", file=sys.stderr)
        return 2

    model = to_model(courses, args)
    text = json.dumps(model, indent=2, ensure_ascii=False) + "\n"

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf8")
        for c in courses:
            points = sum(len(t.points) for t in c.topics)
            print(
                f"{c.name}: {len(c.topics)} topics, {points} points, "
                f"{len(c.outcomes)} outcomes",
                file=sys.stderr,
            )
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(text)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
